name: Bug Report
description: Report a bug or issue with this plugin
labels: ["bug"]
assignees:
  - ybw0014
body:
  - type: markdown
    attributes:
      value: |
        ## Welcome to the SlimefunGuguProject issue tracker
        You are reporting a bug in the localized (Chinese) version of CrystamaeHistoria.
        For feedback and suggestions, please visit the [QQ group](https://50l.cc/gugu-qgroup).
        Please read [this guide](https://slimefun-wiki.guizhanss.cn/How-to-report-bugs) for instructions on how to report bugs correctly.

        <strong><i>You must fill in fields marked with an asterisk (*)</i></strong>

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following before reporting
      options:
        - label: You are using a build downloaded from the official build server
          required: true
        - label: You have verified the checksum of the downloaded files and confirmed they downloaded correctly
          required: true
        - label: You have not modified the downloaded files
          required: true
        - label: You have searched the [known issues list](https://github.com/SlimefunGuguProject/CrystamaeHistoria/issues) and did not find the same issue
          required: true

  - type: textarea
    id: description
    attributes:
      label: Problem description
      description: |
        Describe the issue you are reporting in detail.
        Providing detailed information helps us address the problem faster.
      placeholder: Saying only "It doesn't work" won't help developers reproduce the issue.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: |
        Describe in detail how to reproduce this issue.
        If you have a video, please include a link here.
      placeholder: |
        1. xxx
        2. xxx
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: |
        What do you expect to happen?
        Sometimes the issue is caused by a misunderstanding of a feature.
    validations:
      required: true

  - type: input
    id: server-log
    attributes:
      label: Server log
      description: |
        Check the server logs for any errors. If present, upload them to [https://paste.guizhanss.net/](https://paste.guizhanss.net/) and paste the link here.
        **Do not paste logs directly into this field.**
      placeholder: https://paste.guizhanss.net/...
    validations:
      required: false

  - type: input
    id: error-report
    attributes:
      label: Error report
      description: |
        If the server log references files in `/plugins/Slimefun/error-reports` (error reports),
        upload them to [https://paste.guizhanss.net/](https://paste.guizhanss.net/) and paste the link here.
        **Do not paste error reports directly into this field.**
      placeholder: https://paste.guizhanss.net/...
    validations:
      required: false

  - type: dropdown
    id: server-software
    attributes:
      label: Server software
      description: Please select the server software you are using
      options:
        - Spigot
        - Paper
        - Purpur
        - Airplane
        - Other (please specify in the description)
    validations:
      required: true

  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft version
      description: Please enter your Minecraft version
    validations:
      required: true

  - type: textarea
    id: slimefun-version
    attributes:
      label: Slimefun version
      description: |
        Please provide the Slimefun version
        (e.g. v4.9-canary-08120db)
        If you have admin access, run `/sf versions`, screenshot it and attach the entire output here.
    validations:
      required: true

  - type: input
    id: version-plugin
    attributes:
      label: Plugin version
      description: |
        Please provide the plugin version
        (e.g. Build 1 (git x114514))
    validations:
      required: true
